---
title    : "F-distribution & Non-parametric tests"
author   : "Klinkenberg"
date     : "4 oct 2021"
output: 
  revealjs::revealjs_presentation:
    template: http://shklinkenberg.github.io/uva_style/UvAtemplate.html
    theme: white #simple #black
    highlight: pygments
    transition: slide #fade #slide
    background_transition: slide
    center: true
    self_contained: false
    includes       :
      in_header    : "../../../GA_Script/GA_Script.html"
  html_document:
    toc            : TRUE
    self_contained : false
    toc_float:
      collapsed    : FALSE
      smooth_scroll: TRUE
    includes       :
      in_header    : "../../../GA_Script/GA_Script.html"
---

```{r setup, include=FALSE}
# Display plots on next slide in IOslides
# smaller in the above YAML must be off to make this work.

library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    paste0('\n\n----\n\n', hook_plot(x, options))
  })
})
```

```{r child="../../../topics/f_distribution/f_distribution.Rmd"}
```

```{r child="../../../topics/non_parametric_concept/non_parametric_concept.Rmd", eval=TRUE}
```

```{r child="../../../topics/kruskal_wallis_test/kruskal_wallis_test.Rmd", eval=T}
```


<!-- Footer insert below -->

```{r child="../../../footer.md"}
```
