---
title: "Bayes"
subtitle: "Parameter estimation & hypothesis testing"
author: "Klinkenberg"
date: "22 oct 2021"
output: 
  revealjs::revealjs_presentation:
    template: http://shklinkenberg.github.io/uva_style/UvAtemplate.html
    theme: white #simple #black
    highlight: pygments
    transition: slide #fade #slide
    background_transition: slide
    center: true
    self_contained: false
    includes       :
      in_header    : "../../../GA_Script/GA_Script.html"
  html_document:
    toc            : TRUE
    self_contained : false
    toc_float:
      collapsed    : FALSE
      smooth_scroll: TRUE
    includes       :
      in_header    : "../../../GA_Script/GA_Script.html"
---

```{r setup, include=FALSE, eval=T}
# Display plots on next slide in IOslides
# smaller in the above YAML must be off to make this work.

library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    paste0('\n\n----\n\n', hook_plot(x, options))
  })
})
```

# 

$$\large P(H \mid D) = \frac{P(D \mid H) \times P(H)}{P(D)}$$

##

$$\underbrace{P(H \mid D)}_{\text{Posterior}} = \underbrace{P(H)}_{\text{Prior}} \times \underbrace{\frac{P(D \mid H)}{P(D)}}_{\text{Likelihood}}$$

## Bayes is about

> Posterior $\propto$ Prior $\times$ Likelihood

* Quantified belief
* Common sense expressed in numbers
* Updating belief in light of new evidence
* Yesterdays posteriors are todays priors

```{r child="../../../topics/bayes/bayesian_parameter_estimation.Rmd"}
```

```{r child="../../../topics/bayes/bayesian_hypothesis_testing.Rmd"}
```

<!-- Footer insert below -->

```{r child="../../../footer.md"}
```
