<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Klinkenberg" />

<meta name="date" content="2020-09-15" />

<title>T-distribution and the  One-sample t-test</title>

<script src="t_distribution_and_one_sample_t_test_handout_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="t_distribution_and_one_sample_t_test_handout_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="t_distribution_and_one_sample_t_test_handout_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="t_distribution_and_one_sample_t_test_handout_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="t_distribution_and_one_sample_t_test_handout_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="t_distribution_and_one_sample_t_test_handout_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="t_distribution_and_one_sample_t_test_handout_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="t_distribution_and_one_sample_t_test_handout_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="t_distribution_and_one_sample_t_test_handout_files/navigation-1.1/tabsets.js"></script>
<link href="t_distribution_and_one_sample_t_test_handout_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="t_distribution_and_one_sample_t_test_handout_files/highlightjs-9.12.0/highlight.js"></script>
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-107432294-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());

  gtag('config', 'UA-107432294-1');
</script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">



<h1 class="title toc-ignore">T-distribution and the <br>One-sample t-test</h1>
<h4 class="author">Klinkenberg</h4>
<h4 class="date">15 sep 2020</h4>

</div>


<div id="inhoud" class="section level2">
<h2>Inhoud</h2>
<div id="toc">

</div>
<!-- Add the required topics below -->
</div>
<div id="t-distribution" class="section level1 section">
<h1>T-distribution</h1>
<div id="gosset" class="section level2 smaller">
<h2>Gosset</h2>
<p><small> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/William_Sealy_Gosset.jpg/800px-William_Sealy_Gosset.jpg" style="float: left; width: 150px; margin: 0 20px 0 0;"></p>
<p>In probability and statistics, Student’s t-distribution (or simply the t-distribution) is any member of a family of continuous probability distributions that arises when estimating the mean of a normally distributed population in situations where the sample size is small and population standard deviation is unknown.</p>
<p>In the English-language literature it takes its name from William Sealy Gosset’s 1908 paper in Biometrika under the pseudonym “Student”. Gosset worked at the Guinness Brewery in Dublin, Ireland, and was interested in the problems of small samples, for example the chemical properties of barley where sample sizes might be as low as 3.</p>
<p>Source: <a href="https://en.wikipedia.org/wiki/Student%27s_t-distribution">Wikipedia</a></p>
<p><img style="float: right; mix-blend-mode: multiply; width:300px;" src="https://i.vimeocdn.com/video/432998159_1280x768.jpg"></p>
<p></small></p>
</div>
<div id="population-distribution" class="section level2 smaller subsection">
<h2>Population distribution</h2>
<pre class="r"><code>layout(matrix(c(2:6,1,1,7:8,1,1,9:13), 4, 4))

n  = 56    # Sample size
df = n - 1 # Degrees of freedom

mu    = 100
sigma = 15

IQ = seq(mu-45, mu+45, 1)

par(mar=c(4,2,2,0))  
plot(IQ, dnorm(IQ, mean = mu, sd = sigma), type=&#39;l&#39;, col=&quot;red&quot;, main = &quot;Population Distribution&quot;)

n.samples = 12

for(i in 1:n.samples) {
  
  par(mar=c(2,2,2,0))  
  hist(rnorm(n, mu, sigma), main=&quot;Sample Distribution&quot;, cex.axis=.5, col=&quot;beige&quot;, cex.main = .75)
  
}</code></pre>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="t-statistic" class="section level2 subsection">
<h2>T-statistic</h2>
<p><span class="math display">\[T_{n-1} = \frac{\bar{x}-\mu}{SE_x} = \frac{\bar{x}-\mu}{s_x / \sqrt{n}}\]</span></p>
<p>So the t-statistic represents the deviation of the sample mean <span class="math inline">\(\bar{x}\)</span> from the population mean <span class="math inline">\(\mu\)</span>, considering the sample size, expressed as the degrees of freedom <span class="math inline">\(df = n - 1\)</span></p>
</div>
<div id="a-sample" class="section level2 smaller">
<h2>A sample</h2>
<p>Let’s take one sample from our normal populatiion and calculate the t-value.</p>
<pre class="r"><code>x = rnorm(n, mu, sigma); x</code></pre>
<pre><code>##  [1]  90.51016 101.16480  94.92502  86.06866 115.09797  96.43774 101.04681 137.65171 119.66889
## [10]  94.84335 108.75063 106.34414  83.14934  81.78539 111.10440 103.55524  89.27323 123.68869
## [19]  93.64828  59.77954 105.18172 104.37688  94.22584 103.90144  66.26008  94.99329 105.86573
## [28] 104.53662  90.38902  74.50135  73.56612  93.78079 114.56605  83.56902 108.10363  64.36580
## [37] 109.44024  82.95905 126.40673 107.50969 124.10399  97.85034 131.05859 111.35334  88.48276
## [46] 104.60590  89.28268 103.54148 131.33135  87.55978  96.91265  90.23557  82.88881 122.46896
## [55] 111.61067  87.25521</code></pre>
<pre class="r"><code>hist(x, main = &quot;Sample distribution&quot;, col = &quot;beige&quot;)
text(80, 10, round(mean(x),2))</code></pre>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="t-value" class="section level2">
<h2>t-value</h2>
<p><span class="math display">\[T_{n-1} = \frac{\bar{x}-\mu}{SE_x} = \frac{\bar{x}-\mu}{s_x / \sqrt{n}}\]</span></p>
<pre class="r"><code>t = (mean(x) - mu) / (sd(x) / sqrt(n))
t</code></pre>
<pre><code>## [1] -0.2575259</code></pre>
</div>
<div id="more-samples" class="section level2">
<h2>More samples</h2>
<p>let’s take more samples.</p>
<pre class="r"><code>n.samples     = 1000
mean.x.values = vector()
se.x.values   = vector()

for(i in 1:n.samples) {
  x = rnorm(n, mu, sigma)
  mean.x.values[i] = mean(x)
  se.x.values[i]   = (sd(x) / sqrt(n))
}</code></pre>
</div>
<div id="mean-and-se-for-all-samples" class="section level2">
<h2>Mean and SE for all samples</h2>
<pre class="r"><code>head(cbind(mean.x.values, se.x.values))</code></pre>
<pre><code>##      mean.x.values se.x.values
## [1,]      97.80148    2.058823
## [2,]     107.73420    2.092620
## [3,]     100.14699    2.187660
## [4,]     102.63304    1.866385
## [5,]     102.70998    1.980412
## [6,]     101.07697    2.087270</code></pre>
</div>
<div id="sampling-distribution" class="section level2">
<h2>Sampling distribution</h2>
<pre class="r"><code>hist(mean.x.values, 
     col  = &quot;beige&quot;, 
     main = &quot;Sampling distribution&quot;, 
     xlab = &quot;all sample means&quot;)</code></pre>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="calculate-t-values" class="section level2">
<h2>Calculate t-values</h2>
<p><span class="math display">\[T_{n-1} = \frac{\bar{x}-\mu}{SE_x} = \frac{\bar{x}-\mu}{s_x / \sqrt{n}}\]</span></p>
<pre class="r"><code>t.values = (mean.x.values - mu) / se.x.values

tail(cbind(mean.x.values, mu, se.x.values, t.values))</code></pre>
<pre><code>##         mean.x.values  mu se.x.values    t.values
##  [995,]     100.10709 100    2.251806  0.04755756
##  [996,]      97.92625 100    1.788580 -1.15943763
##  [997,]     100.78829 100    2.167220  0.36373449
##  [998,]     100.46998 100    2.022490  0.23237926
##  [999,]      98.46366 100    2.232258 -0.68824474
## [1000,]     100.72427 100    1.920569  0.37711423</code></pre>
</div>
<div id="sampled-t-values" class="section level2">
<h2>Sampled t-values</h2>
<p>What is the distribution of all these t-values?</p>
<pre class="r"><code>hist(t.values, 
     freq = F, 
     main = &quot;Sampled T-values&quot;, 
     xlab = &quot;T-values&quot;,
     col  = &quot;beige&quot;,
     ylim = c(0, .4))
T = seq(-4, 4, .01)
lines(T, dt(T,df), col = &quot;red&quot;)
legend(&quot;topright&quot;, lty = 1, col=&quot;red&quot;, legend = &quot;T-distribution&quot;)</code></pre>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
</div>
<div id="t-distribution-1" class="section level2 smaller">
<h2>T-distribution</h2>
<p><small> So if the population is normaly distributed (assumption of normality) the t-distribution represents the deviation of sample means from the population mean (<span class="math inline">\(\mu\)</span>), given a certain sample size (<span class="math inline">\(df = n - 1\)</span>).</p>
<p>The t-distibution therefore is different for different sample sizes and converges to a standard normal distribution if sample size is large enough.</p>
<p>The t-distribution is defined by:</p>
<p><span class="math display">\[\textstyle\frac{\Gamma \left(\frac{\nu+1}{2} \right)} {\sqrt{\nu\pi}\,\Gamma \left(\frac{\nu}{2} \right)} \left(1+\frac{x^2}{\nu} \right)^{-\frac{\nu+1}{2}}\!\]</span></p>
<p>where <span class="math inline">\(\nu\)</span> is the number of degrees of freedom and <span class="math inline">\(\Gamma\)</span> is the gamma function.</p>
<p>Source: <a href="https://en.wikipedia.org/wiki/Student%27s_t-distribution">wikipedia</a></p>
<p></small></p>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="one-or-two-sided" class="section level2 subsection">
<h2>One or two sided</h2>
<p>Two sided</p>
<ul>
<li><span class="math inline">\(H_A: \bar{x} \neq \mu\)</span></li>
</ul>
<p>One sided</p>
<ul>
<li><span class="math inline">\(H_A: \bar{x} &gt; \mu\)</span></li>
<li><span class="math inline">\(H_A: \bar{x} &lt; \mu\)</span></li>
</ul>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="effect-size" class="section level2 subsection">
<h2>Effect-size</h2>
<p>The effect-size is the standardised difference between the mean and the expected <span class="math inline">\(\mu\)</span>. In the t-test effect-size is expressed as <span class="math inline">\(r\)</span>.</p>
<p><span class="math display">\[r = \sqrt{\frac{t^2}{t^2 + \text{df}}}\]</span></p>
<pre class="r"><code>r = sqrt(t^2/(t^2 + df))

r</code></pre>
<pre><code>## [1] 0.2603778</code></pre>
</div>
<div id="effect-size-distribution" class="section level2 smaller">
<h2>Effect-size distribution</h2>
<p><small> We can also calculate effect-sizes for all our calculated t-values. Under the assumption of <span class="math inline">\(H_0\)</span> the effect-size distribution looks like this.</p>
<pre class="r"><code>r = sqrt(t.values^2/(t.values^2 + df))

tail(cbind(mean.x.values, mu, se.x.values, t.values, r))</code></pre>
<pre><code>##         mean.x.values  mu se.x.values    t.values           r
##  [995,]     100.10709 100    2.251806  0.04755756 0.006412529
##  [996,]      97.92625 100    1.788580 -1.15943763 0.154462270
##  [997,]     100.78829 100    2.167220  0.36373449 0.048987064
##  [998,]     100.46998 100    2.022490  0.23237926 0.031318642
##  [999,]      98.46366 100    2.232258 -0.68824474 0.092405837
## [1000,]     100.72427 100    1.920569  0.37711423 0.050784457</code></pre>
<pre class="r"><code>hist(r, main = &quot;effect-size distribution&quot;, col = &quot;beige&quot;)</code></pre>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Cohen (1988)</p>
<ul>
<li>Small: 0 &lt;= .1</li>
<li>Medium: .1 &lt;= .3</li>
<li>Large: .3 &lt;= .5</li>
</ul>
<p></small></p>
</div>
<div id="power" class="section level2 subsection">
<h2>Power</h2>
<ul>
<li>Strive for 80%</li>
<li>Based on know effect size</li>
<li>Calculate number of subjects needed</li>
<li>Use <a href="http://www.gpower.hhu.de">G*Power</a> to calculate</li>
</ul>
<p><img src="http://www.gpower.hhu.de/fileadmin/redaktion/Fakultaeten/Mathematisch-Naturwissenschaftliche_Fakultaet/Psychologie/AAP/gpower/GPowerIcon.png" /></p>
</div>
<div id="alpha-power" class="section level2 smaller">
<h2>Alpha Power</h2>
<pre class="r"><code>T = seq(-3,6,.01)
N = 45
E = 2

# Set plot
plot(0,0,
     type = &quot;n&quot;,
     ylab = &quot;Density&quot;,
     xlab = &quot;T&quot;,
     ylim = c(0,.5),
     xlim = c(-3,6),
     main = &quot;T-Distributions under H0 and HA&quot;)

critical_t = qt(.05,N-1,lower.tail=FALSE)

# Alpha
range_x = seq(critical_t,6,.01)
polygon(c(range_x,rev(range_x)),
        c(range_x*0,rev(dt(range_x,N-1,ncp=0))),
        col     = &quot;grey&quot;,
        density = 10,
        angle   = 90,
        lwd     = 2)

# Power
range_x = seq(critical_t,6,.01)
polygon(c(range_x,rev(range_x)),
        c(range_x*0,rev(dt(range_x,N-1,ncp=E))),
        col     = &quot;grey&quot;,
        density = 10,
        angle   = 45,
        lwd     = 2)

lines(T,dt(T,N-1,ncp=0),col=&quot;red&quot;, lwd=2) # H0 line
lines(T,dt(T,N-1,ncp=E),col=&quot;blue&quot;,lwd=2) # HA line

# Critical value
lines(rep(critical_t,2),c(0,dt(critical_t,N-1,ncp=E)),lwd=2,col=&quot;black&quot;)
text(critical_t,dt(critical_t,N-1,ncp=E),&quot;critical T-value&quot;,pos=2, srt = 90)

# H0 and HA
text(0,dt(0,N-1,ncp=0),expression(H[0]),pos=3,col=&quot;red&quot;, cex=2)
text(E,dt(E,N-1,ncp=E),expression(H[A]),pos=3,col=&quot;blue&quot;,cex=2)

# Mu H0 line
lines(c(0,0),c(0,dt(0,N-1)), col=&quot;red&quot;,  lwd=2,lty=2)
text(0,dt(0,N-1,ncp=0)/2,expression(mu),pos=4,cex=1.2)
# Mu HA line
lines(c(E,E),c(0,dt(E,N-1,ncp=E)),col=&quot;blue&quot;,lwd=2,lty=2)
text(E,dt(0,N-1,ncp=0)/2,expression(paste(mu)),pos=4,cex=1.2)

# t-value
lines( c(critical_t+.01,6),c(0,0),col=&quot;green&quot;,lwd=4)

# Legend
legend(&quot;topright&quot;, c(expression(alpha),&#39;POWER&#39;),density=c(10,10),angle=c(90,45))</code></pre>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-16-1.png" width="768" /></p>
<hr />
<iframe src="http://rpsychologist.com/d3/NHST/#viz">
</iframe>
<p><a href="http://rpsychologist.com/d3/NHST/#viz">R-Psychologist</a></p>
</div>
</div>
<div id="one-sample-t-test" class="section level1 section">
<h1>One-sample t-test</h1>
<div id="iq-next-to-you" class="section level2 flexbox vcenter">
<h2>IQ next to you</h2>
<p><img src="../../../../topics/t-test_one-sample/QR_iq.png" alt="http://goo.gl/T6Lo2s" /> <br> <a href="http://goo.gl/T6Lo2s" class="uri">http://goo.gl/T6Lo2s</a></p>
</div>
<div id="models" class="section level2 flexbox vcenter">
<h2>Models</h2>
<div style="font-size:200%; transform: rotate(-11deg);">
<p><span class="math display">\[\text{outcome} = \text{model} + \text{error}\]</span></p>
</div>
</div>
<div id="compare-sample-mean" class="section level2 smaller">
<h2>Compare sample mean</h2>
<p><small> We use the one-sample t-test to compare the sample mean <span class="math inline">\(\bar{x}\)</span> to the population mean <span class="math inline">\(\mu\)</span>.</p>
<p>Let’s take a different sample of n = 43 and calculate the mean of this sample.</p>
<pre class="r"><code>mu     = 120
n      = length(IQ.next.to.you)
x      = IQ.next.to.you
mean_x = mean(x, na.rm = T)
sd_x   = sd(x, na.rm = T)
cbind(n, mean_x, sd_x)</code></pre>
<pre><code>##       n   mean_x     sd_x
## [1,] 49 122.3265 7.684909</code></pre>
<p>Does this mean, differ significantly from the population mean <span class="math inline">\(\mu = 120\)</span>? </small></p>
</div>
<div id="hypothesis" class="section level2 subsection">
<h2>Hypothesis</h2>
<div id="null-hypothesis" class="section level3">
<h3>Null hypothesis</h3>
<ul>
<li><span class="math inline">\(H_0: \bar{x} = \mu\)</span></li>
</ul>
</div>
<div id="alternative-hypothesis" class="section level3">
<h3>Alternative hypothesis</h3>
<ul>
<li><span class="math inline">\(H_A: \bar{x} \neq \mu\)</span></li>
<li><span class="math inline">\(H_A: \bar{x} &gt; \mu\)</span></li>
<li><span class="math inline">\(H_A: \bar{x} &lt; \mu\)</span></li>
</ul>
</div>
</div>
<div id="assumptions" class="section level2">
<h2>Assumptions</h2>
<ul>
<li>Normal samples distribution</li>
<li>Measurement level
<ul>
<li>Interval</li>
<li>Ratio</li>
</ul></li>
</ul>
</div>
<div id="t-statistic-1" class="section level2">
<h2>T-statistic</h2>
<p><span class="math display">\[T_{n-1} = \frac{\bar{x}-\mu}{SE_x} = \frac{\bar{x}-\mu}{s_x / \sqrt{n}} = \frac{122.33 - 120 }{7.68 / \sqrt{49}}\]</span></p>
<p>So the t-statistic represents the deviation of the sample mean <span class="math inline">\(\bar{x}\)</span> from the population mean <span class="math inline">\(\mu\)</span>, considering the sample size.</p>
<pre class="r"><code>t = (mean_x - mu) / (sd_x / sqrt(n)); t</code></pre>
<pre><code>## [1] 2.119181</code></pre>
</div>
<div id="type-1-error" class="section level2 subsection">
<h2>Type 1 error</h2>
<p>To determine if this t-value significantly differs from the population mean we have to specify a type I error that we are willing to make.</p>
<ul>
<li>Type I error / <span class="math inline">\(\alpha\)</span> = .05</li>
</ul>
</div>
<div id="p-value-one-sided" class="section level2 subsection">
<h2><em>P</em>-value one sided</h2>
<p>Finally we have to calculate our <em>p</em>-value for which we need the degrees of freedom <span class="math inline">\(df = n - 1\)</span> to determine the shape of the t-distribution.</p>
<pre class="r"><code>df = n - 1; df</code></pre>
<pre><code>## [1] 48</code></pre>
<pre class="r"><code>if(!&quot;visualize&quot; %in% installed.packages()) { install.packages(&quot;visualize&quot;) }
library(&quot;visualize&quot;)

visualize.t(t, df, section = &quot;upper&quot;)</code></pre>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
<div id="p-value-two-sided" class="section level2 subsection">
<h2><em>P</em>-value two sided</h2>
<pre class="r"><code>visualize.t(c(-t, t), df, section = &quot;tails&quot;)</code></pre>
<hr />
<p><img src="t_distribution_and_one_sample_t_test_handout_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<div id="effect-size-1" class="section level2">
<h2>Effect-size</h2>
<p><span class="math display">\[r = \sqrt{\frac{t^2}{t^2 + \text{df}}}\]</span></p>
<pre class="r"><code>r = sqrt(t^2/(t^2 + df))

r</code></pre>
<pre><code>## [1] 0.2925001</code></pre>
<!-- Footer insert below -->
</div>
</div>
<div id="end" class="section level1">
<h1>End</h1>
<div id="contact" class="section level2">
<h2>Contact</h2>
<script src="https://use.fontawesome.com/23c1d38eea.js"></script>
<ul class="fa-ul" style="color:black; list-style:none;">
<li>
<i class="fa-li fa fa-twitter"></i> <a href="https://twitter.com/shklinkenberg" target="_blank" style="color:black; border-bottom:none;"><span class="citation">@shklinkenberg</span></a>
</li>
<li>
<i class="fa-li fa fa-linkedin-square"></i> <a href="https://www.linkedin.com/in/sharonklinkenberg/" target="_blank" style="color:black; border-bottom:none;">Klinkenberg</a>
</li>
<li>
<i class="fa-li fa fa-envelope-o"></i> <a style="unicode-bidi:bidi-override; direction: rtl; color:black" href="javascript:window.location.href = 'mailto:' + ['s.klinkenberg','uva.nl'].join('@')">ln.AvU@grebneknilK.S</a>
</li>
<li>
<i class="fa-li fa fa-github"></i> <a href="https://github.com/ShKlinkenberg" target="_blank" style="color:black; border-bottom:none;">ShKlinkenberg</a>
</li>
</ul>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
