---
title: "Statistical Reasoning"
subtitle: "SSR"
author: "Klinkenberg"
date: "05 sep 2019"
output: 
  ioslides_presentation:
    logo           : https://shklinkenberg.github.io/uva_style/images/logo_uva.png
    smaller        : FALSE
    css            : https://shklinkenberg.github.io/uva_style/new_uva_style.css
    includes       :
      in_header    : ["../../../TOC/TOC_generator.js.wrapper",
                      "../../../GA_Script/GA_Script.html"]
    self_contained : true
  html_document:
    toc            : TRUE
    toc_float:
      collapsed    : FALSE
      smooth_scroll: TRUE
    includes       :
      in_header    : "../../../GA_Script/GA_Script.html"
---

```{r setup, include=FALSE}
# Display plots on next slide in IOslides
# smaller in the above YAML must be off to make this work.

library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    paste0('\n\n----\n\n', hook_plot(x, options))
  })
})
```

## Content

* Statistical Reasoning
* Empirical cycle
* The Null distribution
* Conclusions from premisses

## Learning

<iframe style="height:400px;" src="https://www.youtube.com/embed/JC82Il2cjqA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<!-- Add the required topics below -->

```{r child="../../../topics/statistical_reasoning/statistical_reasoning.Rmd"}
```

```{r child="../../../topics/empirical_cycle/empirical_cycle.Rmd"}
```

```{r child="../../../topics/coin_expreiment/coin_experiment.Rmd"}
```

<!-- Footer insert below -->

```{r child="../../../footer.md"}
```

