# Bayes Theorem {.section}

## Bayes rule

$$\large P(A\mid B) = \frac{P(B \mid A) P(A)}{P(B)}$$

## Conditional probabilities

$P(A \mid B) = \frac{P(B \mid A) P(A)}{P(B)}$

<table style="border: none;  transform: scale(1);">
  <col width="150px">
  <col width="225px">
  <col width="225px">
<tr><td></td style="width: 300px;">
<td>
$P(A)$
</td style="width: 300px;">
<td>
$P(\neg A)$
</td></tr>
<tr height="150px">
<td>
$\begin{equation}
\begin{aligned}
P(\neg B) = & P(\neg B \mid A) P(A) + \\ 
            & P(\neg B \mid \neg A) P(\neg A)
\end{aligned}
\end{equation}$
</td>
<td style = "border: 5px solid white; padding: 10px; color: white; background-color: red;">
$P(\neg B \mid A)$
</td>
<td style = "border: 5px solid white; padding: 10px; color: black; background-color: lightgreen;">
$P(\neg B \mid \neg A)$
</td>
</tr>
<tr height="150px">
<td>
$\begin{equation}
\begin{aligned}
P(B) = & P(B \mid A) P(A) + \\ 
       & P(B \mid \neg A) P(\neg A)
\end{aligned}
\end{equation}$
</td>   
<td style = "border: 5px solid white; padding: 10px; color: black; background-color: lightgreen;">
$P(B \mid A)$
</td>
<td style = "border: 5px solid white; padding: 10px; color: white; background-color: red;">
$P(B \mid \neg A)$
</td>
</tr>
</table>

## Hypothesis | Data

$$\large P(H \mid D) = \frac{P(D \mid H) \times P(H)}{P(D)}$$
## Posterior Likelihood Prior {.smaller}

$$\underbrace{P(H \mid D)}_{\text{Posterior}} = \underbrace{P(H)}_{\text{Prior}} \times \underbrace{\frac{P(D \mid H)}{P(D)}}_{\text{Likelihood}}$$

* $P(H)$, the $prior$, is the initial degree of belief in $H$.
* $P(H \mid D)$, the $posterior$, is the degree of belief after incorporating news that $D$ is true.
* the quotient $\frac{P(D \mid H)}{P(D)}$ represents the support $D$ provides for $H$.

Posterior $\propto$ Likelihood $\times$ Prior

## Bayes is about

> Posterior $\propto$ Likelihood $\times$ Prior

* Quantified belief
* Common sense expressed in numbers
* Updating belief in light of new evidence
* Yesterdays posteriors are todays priors

## Generative model

Frequentists

> State of the world → Data

Bayesions

> Data → State of the world

## Resources

* [The quick proof of Bayes' theorem - 3Bleu1Brown](https://youtu.be/U_85TaXbeIo)
* [Bayes theorem - 3Blue1Brown](https://youtu.be/HZGCoVF3YvM)
* [Wikipedia](https://en.wikipedia.org/wiki/Bayes%27_theorem)