---
title: "Mediation"
author: "Klinkenberg"
date: "14 nov 2019"
output: 
  ioslides_presentation:
    logo           : https://shklinkenberg.github.io/uva_style/images/logo_uva.png
    smaller        : FALSE
    css            : https://shklinkenberg.github.io/uva_style/new_uva_style.css
    includes       :
      in_header    : ["../../../TOC/TOC_generator.js.wrapper",
                      "../../../GA_Script/GA_Script.html"]
    self_contained : TRUE
  html_document:
    toc            : TRUE
    toc_float:
      collapsed    : FALSE
      smooth_scroll: TRUE
    includes       :
      in_header    : "../../../GA_Script/GA_Script.html"
---


```{r setup, include=FALSE}
# Display plots on next slide in IOslides
# smaller in the above YAML must be off to make this work.

library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    paste0('\n\n----\n\n', hook_plot(x, options))
  })
})
```

## Inhoud

<div id="toc"></div>

<div class="notes">
### Lecture outline

[Weblecture](https://webcolleges.uva.nl/Mediasite/Play/80b621f4a93d4b319d88935de578205b1d)

* 0:00 Mediation example
* 0:10 Paths and regressions
* 0:20 Example in SPSS with regression analysis
* 0:35 Simulation and visual interpretation
* 1:00 AxB == c - c.accent
* 1:05 Effect sizes
* 1:15 Example with Process
* 1:25 Bootstrapping

</div>

<div id="toc"></div>

<!-- Add the required topics below -->

```{r child="../../../topics/mediation/mediation.rmd"}
```


<!-- Footer insert below -->

```{r child="../../../footer.md"}
```

