---
title: "PCA & CB alpha"
subtitle: "Principal component analysis & <br>Cronbach's alpha"
author: "Klinkenberg"
date: "16 jan 2020"
output: 
  ioslides_presentation:
    logo           : https://shklinkenberg.github.io/uva_style/images/logo_uva.png
    smaller        : FALSE
    css            : https://shklinkenberg.github.io/uva_style/new_uva_style.css
    includes       :
      in_header    : ["../../../TOC/TOC_generator.js.wrapper",
                      "../../../GA_Script/GA_Script.html"]
    self_contained : TRUE
  html_document:
    toc            : TRUE
    toc_float:
      collapsed    : FALSE
      smooth_scroll: TRUE
    includes       :
      in_header    : "../../../GA_Script/GA_Script.html"
---

```{r setup, include=FALSE}
# Display plots on next slide in IOslides
# smaller in the above YAML must be off to make this work.

library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    paste0('\n\n----\n\n', hook_plot(x, options))
  })
})
```

## Inhoud

<div id="toc"></div>

<div class="notes">
### Outline

[Weblecture](https://webcolleges.uva.nl/Mediasite/Play/d15f85f4caf64d22901a8af1655226321d)

* 0:00 Conceptual PCA
* 0:24 Collect data on SPSS anxiety 
* 0:30 Example in SPSS (alternate SPSS and assumptions)
* 1:20 Simulations of big 5
* 1:30 Conceptual CBA
* 1:35 Calculations CBA
</div>

<!-- Add the required topics below -->

```{r child="../../../topics/pca_cb_alpha/pca_cb_alpha.Rmd"}
```


<!-- Footer insert below -->

```{r child="../../../footer.md"}
```

