---
title: "Experiment"
author: "Klinkenberg"
date: "06 sep 2017"
output: 
  ioslides_presentation:
    logo           : http://shklinkenberg.github.io/statistics-lectures/template/logo_uva.png
    smaller        : FALSE
    css            : http://shklinkenberg.github.io/statistics-lectures/styles/style.css
    includes       :
      in_header    : ["../../../TOC/TOC_generator.js.wrapper",
                      "../../../GA_Script/GA_Script.html"]
    self_contained : TRUE
    incremental    : TRUE
---

```{r setup, include=FALSE, eval=FALSE}
# Display plots on next slide in IOslides
# smaller in the above YAML must be off to make this work.

library(knitr)
local({
  hook_plot = knit_hooks$get('plot')
  knit_hooks$set(plot = function(x, options) {
    paste0('\n\n----\n\n', hook_plot(x, options))
  })
})
```

## Inhoud

<div id="toc"></div>

<!-- Add the required topics below -->

```{r child = "../../../topics/coin_expreiment/coin_experiment.Rmd"}
```

<!-- Footer insert below -->

```{r child="../../../footer.md"}
```
