# What is Test Utility

## Test Utility

Test Utility, litterally refers to using a test as a utility, as a tool.

### Costs and benefits

* monotary
* non-monotary

The relationship between the costs and benefits are determined by the psychometric properties of the test.

These properties can be emperically tested. We will show you the reasoning process in this lecture.

## Predictive use of tests

* Often we want to predict based on testscores, how an individual will perform at a later time.
* The thing we want to predict is called the **criterion**
    * Example: Selection of good employees or good students
* For a good prediction it is important to have a high correlation between the testscore and the criterion.
* This is called predictive validity / criterion validity

**NOTE:** This is no different than the $R$ and $R^2$ in regular regression, the relation between the outcome and the model.

## CASE STUDY:

Admission test (NL: selectie aan de poort)

* Testweek data from UvA Psychology students
    * Motivation
    * Study results
* The data was gathered before we actually had admission tests (all students where admitted).
* Because of this, we can determine the effectiveness of a supposed admissions procedure.
* We can calculate how much beter our results would be if we had actually selected.
* This comparison will show us how much ther is to gain and the price we have to pay
