---
title: "Test Utility"
author: "Sharon Klinkenberg"
date: "8 june 2021"
---


```{r,echo=FALSE}
set.seed(12)

set.seed(1)
x = round(rnorm(100, 0, 60), 0)
e = round(rnorm(100, 0, 60), 0)

correlation <- cor(x,e)
```


<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/p5.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/addons/p5.dom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.1/addons/p5.sound.min.js"></script>

<script>
let sketch = function(p) {

p.setup = function() {

  p.createCanvas(400, 400);
  p.background('white');
  
  }

p.draw = function() {

  // let a = .5;
  let a = document.getElementById("myRange").value / 100;
  let b = 1 - a;
    
  let w = 400;
  let h = 400;

  let tm = 10;
  let lm = 20;
  let rm = 10;
  let bm = 20;  
  
  let x = [`r x`];
  let e = [`r e`];
  // let y = e;
  // let y = a * x + b * e;
  
  let r = 0;
  const y = [];
  while (r <= 100) {
  y[r] = -a * x[r] + b * e[r] - (tm - ((h-tm-bm)/2)) + tm;
  x[r] += lm + ((w-lm-rm)/2);
  r = r +1;
  }

  p.stroke('black');
  p.strokeWeight(2);
    
  p.rect(lm, tm, w-(lm+rm), h-(tm+bm) );
  
  
  // set axis labels
  // apply rotation only to text hence push and pop
  
  p.push();
  p.strokeWeight(0);
  p.stroke('black');
  p.text('Predictor', w/2, h);
  
  p.translate(10, h/2);
  p.rotate(3.1415/-2);
  p.text('Criterion',0,0);
  p.pop();
    
  // determine if mouse is within plot area
    
  let mX = p.mouseX;
  let mY = p.mouseY; 

        if (mX < w-rm && mX > lm && 
            mY < h-bm && mY > tm) {  
        
        p.strokeWeight(2);
        
        p.fill("red");
        p.rect(lm, tm, mX-lm, mY-tm);
        p.fill("green");
        p.rect(w-rm, tm, mX-w+rm, mY-tm);
        p.fill("green");
        p.rect(lm, h-bm, mX-lm, mY-h+bm);
        p.fill("red");
        p.rect(w-rm, h-bm, mX-w+rm, mY-h+bm);
        
      let FN = 0; // tl
      let TP = 0; // tr
      let TN = 0; // bl
      let FP = 0; // br
      
      for (let i = -1; i <= x.length; i++) {
      
         if(x[i] <= mX && y[i] >  mY) { TN++ } // TN
         if(x[i] <= mX && y[i] <= mY) { FN++ } // FN
         if(x[i] >  mX && y[i] >  mY) { FP++ } // FP
         if(x[i] >  mX && y[i] <= mY) { TP++ } // TP
      
      }
    
     document.getElementById('FN').innerHTML = FN;
     document.getElementById('TP').innerHTML = TP;  
     document.getElementById('TN').innerHTML = TN;  
     document.getElementById('FP').innerHTML = FP;
     
     document.getElementById('r1').innerHTML = FN + TP;
     document.getElementById('r2').innerHTML = TN + FP;  
     document.getElementById('c1').innerHTML = FN + TN;  
     document.getElementById('c2').innerHTML = TP + FP;
     document.getElementById('to').innerHTML = 100; 
     
     document.getElementById('HR').innerHTML = (TP + TN) / 100;
     document.getElementById('BR').innerHTML = (FN + TP) / 100;
     document.getElementById('SEN').innerHTML = (TP / (TP + FN)).toFixed(2);
     document.getElementById('SPE').innerHTML = (TN / (TN + FP)).toFixed(2);

        } // end mouse over
    
    document.getElementById('COR').innerHTML = a;
  
  p.stroke('black');
  p.strokeWeight(5);
        
  let i = 0;
  while (i <= 100) {
  p.point(x[i], y[i]);
  i = i +1;
  }
    
}

}

new p5(sketch, 'container');
</script>

<div style="width:100%;">

<div id='container' style="float:left;"></div>

<div style="float:right; width: 45%;">

### Counts and margins

<table style="width: 150px; height:150px; text-align:center;">
<tr>
<td style="background-color:red;   width: 50px; color:white;" id="FN">FN</td>
<td style="background-color:green; width: 50px; color:white;" id="TP">TP</td>
<td style="width: 50px;" id="r1">0</td>
</tr>
<tr>
<td style="background-color:green; width: 50px; color:white;" id="TN">TN</td>
<td style="background-color:red;   width: 50px; color:white;" id="FP">FP</td>
<td style="width: 50px;" id="r2">0</td>
</tr>
<tr>
<td style="width: 50px;" id="c1">0</td>
<td style="width: 50px;" id="c2">0</td>
<td style="width: 50px;" id="to">0</td>
</tr>
</table>

**What is the:**

* Correlation: <span id="COR"></span>
* Hit Rate: <span id="HR"></span>
* Base Rate: <span id="BR"></span>
* Sensitivity: <span id="SEN"></span>
* Specificity: <span id="SPE"></span>

<div style="width:60%; display: inline;">
Correlation between 0 and 1:
  <input style="width:50%;" type="range" min="0" max="100" value="50" class="slider" id="myRange">
</div>

</div>
</div>